### ISSUE TITLE
Add config struct for newBGP() function

### ISSUE THREAD

**Issue by invidian** [equinix/cloud-provider-equinix-metal#102]
It currently takes 7 parameters and #101 adds 8th, so it's definitely time to move that to dedicated struct.

**Comment by displague** [comment]
Noting that this function is still taking too many parameters:
https://github.com/equinix/cloud-provider-equinix-metal/blob/c45661b89a52516c12b4e4892349bdc5029bd233/metal/bgp.go#L21
