### ISSUE TITLE
Makefile: platforms joining doesn't work

### ISSUE THREAD

**Issue by invidian** [equinix/cloud-provider-equinix-metal#104]
Currently, trying to run locally `make release` fails with the following error for me:
```
bgp-node-selector-amd64: digest: sha256:bf058f9eef5ce126feb1d8d097f2d6597917d997481c770fd132772125e37212 size: 739
make[2]: Leaving directory '/home/invidian/repos/kinvolk/packet-ccm'
# path to credentials based on manifest-tool's requirements here https://github.com/estesp/manifest-tool#sample-usage
/home/invidian/go/bin/manifest-tool push from-args --platforms linux/arm64 linux/amd64, --template quay.io/invidian/packet-ccm:bgp-node-selector-ARCH --target quay.io/invidian/packet-ccm:bgp-node-selector
FATA[0000] You must specify all three arguments --platforms, --template and --target
make[1]: *** [Makefile:198: push-manifest] Error 1
make[1]: Leaving directory '/home/invidian/repos/kinvolk/packet-ccm'
make: *** [Makefile:267: release] Error 2
```

**Comment by deitch** [comment]
I am curious why you ever would want to do `make release` locally. It pushes properly tagged release images out to the hub. We are looking to replace that whole (rather ugly) bit with a single GH action.

**Comment by invidian** [comment]
>I am curious why you ever would want to do make release locally. It pushes properly tagged release images out to the hub. We are looking to replace that whole (rather ugly) bit with a single GH action.

I wanted to build and push Docker images for testing and tinkering with Makefile led me to this command :smile:

**Comment by deitch** [comment]
I get it. I am working on replacing it with the official docker github action. Unless you have a real need for this command, I would like to see it go away.

**Comment by invidian** [comment]
It would be great if there was a clear documentation on how to build multi-arch Docker image for a current code/commit locally, that would be the desired state for me :)

**Comment by deitch** [comment]
`make build` builds the binary, `make image` builds the current one. `make image-all` should do all.

**Comment by deitch** [comment]
I have a PR in progress; I can make `make help` better for that

**Comment by invidian** [comment]
I recall I had some issues with `make image-all`. Also, it does not push the images.

**Comment by deitch** [comment]
Yeah, the pushing should only happen via CI. There is an open PR #124

**Comment by invidian** [comment]
Okay, but if I want to push my dev image somewhere to test it on my cluster, then this must be done manually :/

**Comment by deitch** [comment]
Yeah, fair enough. Not that it is too hard to do `docker push <someimage>`. It is with the multiple images and multi-arch indexes that it gets messy.

**Comment by deitch** [comment]
@invidian #124 merged in, you can run `make help` now and get all of the make targets. It is significantly simplified now too.

The question remaining is, is there a workflow you want to do that is missing, specifically what is it, and should it be in here? If it is building the images, then you can do `make image ARCH=arm64` or `make image-all` and be done.

**Comment by invidian** [comment]
@deitch so while working on Lokomotive, my workflow was to build and push single-arch new CCM image, patch deployment manually on my cluster to see if it's working fine, then build and push multi-arch image, modify Lokomotive code to use it and let it be tested by our e2e tests, which requires multi-arch images to pass.

I looked at `make image-all` and it seems to work nicely now. I think the only thing missing for me right now would be a make target to build a multi-arch manifest and push it. Do you think this is something we could add?

**Comment by deitch** [comment]
@invidian as long as it doesn't overly complicate the makefile, sure. I am still not 100% sure of the flow you want, so open a PR that reflects it? It should be straightforward, as you are hitting a single file.

**Comment by invidian** [comment]
>@invidian as long as it doesn't overly complicate the makefile, sure. I am still not 100% sure of the flow you want, so open a PR that reflects it? It should be straightforward, as you are hitting a single file.

Sure, I'll have a look!

**Comment by invidian** [comment]
Created #126 to address this.
