### ISSUE TITLE
Service watcher is started even though there is nothing to do for it

### ISSUE THREAD

**Issue by invidian** [equinix/cloud-provider-equinix-metal#106]
Currently, even if elastic IP tag is not set, CCM tries to watch Service objects and every loop prints similar messages:
```
failed to update and sync service for add default/kubernetes: elastic ip tag is empty. Nothing to do
```

I think if there is no loops accessing the Service objects, watch could not even be started to save resources. Optionally, RBAC grant can then also be reduced to not need to read service objects, following least privileged principle.

**Comment by deitch** [comment]
The whole structure of CPEM has changed since this issue was opened. We also removed the errors that were reporting the above.
