### ISSUE TITLE
Consider switching to controller-runtime

### ISSUE THREAD

**Issue by invidian** [equinix/cloud-provider-equinix-metal#146]
To simplify logic of setting the controller up and various reconcilers, I think it would be possible to switch for [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) and to set up reconcilers for both Node and Service objects. It would take care of caching etc and should make CCM easier to test I think.

**Comment by deitch** [comment]
Since we simplified them all to use the proper calls from k8s.io/cloud-provider, this is not necessary.
