### ISSUE TITLE
Where should config live?

### ISSUE THREAD

**Issue by deitch** [equinix/cloud-provider-equinix-metal#157]
CCM requires two "secret" bits of information - apiToken and projectID (although arguably project ID isn't _really_ secret) and lots of config:

* facility
* load balancer config URL
* EIP tag
* etc

Many of these config vars have defaults, others don't. All can be set via env vars or (higher priority) command-line flags, and we indicate as such in the README.

These also _all_ can be set in the secret. This actually is more convenient when running in k8s, because it means no need to muck around with the deployment yaml. The env vars and CLI flags are more convenient when running standalone, e.g. debugging or other modes, or for fixed yaml scenarios (where you don't want the config in the secret to be the final word).

On the other hand, these are no so much "secrets", and it is odd to mix these in with the secret.

This ambivalent attitude towards config-in-secret comes out in the docs, where the README doesn't even mention that you can set them there, yet you can.

We need to get past the ambivalent nature and be consistent and clear about it. Our options:

* do not support config in secret, so remove it entirely. You set secret in the secret, config in CLI/env vars. If you need it, modify the yaml. Call this, "make the code match the docs."
* do not support config in secret, instead support a configmap, update the README. This has a higher deployment burden, but keeps secret and config separate.
* fully support config in secret, so update the README to describe it. Call this, "make the docs match the code."
* do not support config in secret (like the first option), add a Helm chart so that it can be parametrized.

Any others? Looking for input from @displague @thebsdbox @gianarb @detiber

**Comment by displague** [comment]
@deitch I've been exploring some of these concerns in https://github.com/packethost/packngo/issues/189. 

I would like to see one layered config file that could be used to provide defaults scoped at various layers: Equinix, Metal, Project, Tool.

The last bit of thinking on that is captured in https://github.com/packethost/packngo/issues/189#issuecomment-802272047 and I have a PR that starts to implement this in https://github.com/packethost/packngo/pull/252.

This is a topic that I am very interested in but I have not been able to find the time to implement fully.  I would love to see a common format used to bring configuration standards to our tools across all languages, while also providing features like 'default metro', 'default plan' to tools that could benefit from that (each tool could decide what they want to do with that information, but it would become conventional to use these values when available).

**Comment by displague** [comment]
I don't have the issues or posts to refer to handy, but some projects prefer to offer configuration via file over environment.

If packngo's configuration was read in from standard paths, the user could choose between a secret or configmap and mount that as a volume to the pod in a location that packngo understands.  Our default installation would assume either configmap or secret.

Packngo doesn't need to concern itself with CCM specific configuration, so those values would be stored in a separate configmap. Should this be supplied as a combination of command line arguments `--config-file` and mounted volumes or environment variables?

I'm a fan of providing multiple ways to configure the tool, 12 factor app-ishly.
I don't think that the CCM, born a Kubernetes app with k8s opinions and conventions, necessarily loses any need for configurability.

If I had to boil all of this to one of your options, `make the docs match the code`, which also seems like the path of least resistance.

**Comment by detiber** [comment]
So, I tend to agree with @displague here, I like the idea of supporting multiple methods, even if we prefer and default to a single solution.

The other thing to note is that config by secret/configmap can be done in multiple ways:
- mounting the configmap/secret as a volume and accessing it directly with the app
- populating env variables from the contents

The main downside to using env variables from configmap/secret is that updates to the configmap/secret require restarting of the pod to take effect, where accessing the contents of the configmap/secret directly through volumemounts would allow for picking up new configuration without restarting, but I'm not sure that is overly important for this use case.

The configmap/secret options do make it easier for users to configure rather than forcing them to modify the deployment to change settings, so whatever approach we take, I think this is an option that we should formally support

**Comment by deitch** [comment]
A few things.

First, I really like your thoughts on a standard configuration for packngo, which can be inherited by whatever tools use it. I assume by "layered", you mean that whatever specific configs are required for a specific downstream tool would be layered on top of the standard configs. I am very interested to see where that goes.

Second, I am hearing the desire to support env var + CLI + "kubernetes config resource" (of which there are multiple types).

Finally, I am hearing, for now, the path of least resistance is to let customers use the secret to configure CCM for all of its options, and update the docs to express it.

At some point, as the "standard packngo config way" evolves, we can evolve CCM to move with it, but not worry about it for right now.

Thanks for the input. I will move down that path.

**Comment by deitch** [comment]
Closing issue, as got the answers we wanted, but feel free to comment more here.

**Comment by deitch** [comment]
Addressed in #162 . As soon as I get a review, will merge in
