### ISSUE TITLE
define zone topology using EM metro

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#164]
Assuming Metros (https://metal.canny.io/changelog/new-metros-feature-live) fits the categorical description of Kubernetes Topology Zones,  https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone, the CCM should annotation nodes with the Equinix Metal "metro" as the zone.

Every EM device instance (those created before Metros and after) have a metro field value.
* https://github.com/packethost/packngo/blob/master/devices.go#L57

**Comment by detiber** [comment]
Following up on the conversation in #183, I think we would be better to treat "metros" as a "region" for Kubernetes topology, and keep facility as the "zone". This would require adding support for InstancesV2.
