### ISSUE TITLE
include required static routes in the documentation or a daemonset 

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#165]
Clusters choosing to use MetalLB must add static routes:

```sh
GATEWAY_IP=$(curl https://metadata.platformequinix.com/metadata | jq -r ".network.addresses[] | select(.public == false) | .gateway")
ip route add 169.254.255.1 via $GATEWAY_IP
ip route add 169.254.255.2 via $GATEWAY_IP
```

This is not covered in the documentation.  It should be covered especially for those users that want to bring their own MetalLB of KubeVIP and will not be using the documented manifests.

Questions:
* Is this necessary for KubeVIP too?
* Could this be bundled as a DaemonSet to simplify the experience? If so, should this be added to the manifest-guided install, guarded behind flags?
* Is a DaemonSet run too late in the process? Do these routes need to be defined above Kubernetes, and if so, should a Kubernetes manifest be used to set that local configuration?

**Comment by deitch** [comment]
This is a longstanding issue, and one of several reasons why we have been recommending people use kubevip over metallb, where feasible.

The fundamental problem is that the BGP peering packets need to go to `169.255.254.1` / `169.254.255.2` from the _private_ IP of the host, but the default route is via the _public_ IP, so the source address ends top being the public IP and the packets are dropped.

The additional static routes are one way to solve this. Another is for the bgp peering software (metallb, kube-vip, etc.) to use the source IP explicitly. bird does this just fine, I believe kube-vip supports it as well (@thebsdbox can you confirm?), and CPEM sets the desired source address for these packets on the annotation `"metal.equinix.com/src-ip"` (configurable).

I believe we looked at doing this via a daemonset in the past, but there was a real reluctance to add all of the infrastructure to CPEM:

* another image to be built and maintained
* a daemonset to be deployed, and customers to wonder what it is, when right now it is just a single pod in a single deployment

all to support something that already works fine with kube-vip and other software that can set source IP.

I don't mind adding a section to the documentation to express it, but I would be hesitant to add build time and run time overhead for this.
