### ISSUE TITLE
BGP sessions established from wrong source address

### ISSUE THREAD

**Issue by flokli** [equinix/cloud-provider-equinix-metal#178]
Disciaimer: This is not a bug in cloud-provider-equinix-metal itself, but it causes a bunch of problems and I thought it might help to make you aware of this, and connect the different issues.

I did install cloud-provider-equinix-metal and MetalLB in a cluster. 
BGP automatically got enabled in the project, enabled for each node. MetalLB got its peers configured, and for each `LoadBalancer` type Service, an Elastic IP was requested, added to the `External-IP` field, and MetalLB tried to announce them. All good :+1: 

However, BGP sessions failed to get established.

After quite some digging, I realized that the Equinix Metal BGP servers only seem to accept connections initiated with the "private ipv4" as a source address. There was simply no reply when using the Public IPv4 address, which is the default for Ubuntu.

I'm not sure if that could be changed, and the BGP servers also allow connections from the Public IPv4 address - that would avoid all the workarounds below.

I was able to manually workaround this, by explicitly configuring a custom static route to the 2 BGP link-local endpoint addresses, similar to:

```
ip r add 169.254.255.1 via $gateway_ipv4 dev bond0 src $private_ipv4
ip r add 169.254.255.2 via $gateway_ipv4 dev bond0 src $private
```

… but this is not very pretty.

I digged deeper - it seems MetalLB doesn't support specifying a custom source address as a field, and most efforts in that direction seem to have stalled (https://github.com/metallb/metallb/issues/670, https://github.com/metallb/metallb/pull/672, https://github.com/metallb/metallb/pull/593)

Something simple such as https://github.com/metallb/metallb/pull/672 would in theory work here, as `cloud-provider-equinix-metal` creates individual peers with node selectors, and does know about the private and public IP addresses of a node.

**Comment by flokli** [comment]
> running those static routes on every host

Yeah, that's what I did now, but it requires some very annoying poking around in `/etc/network/interfaces`:

```
private_ipv4=$(curl -sf https://metadata.platformequinix.com/metadata | jq -r '.network.addresses | map(select(.public==false and .management==true and .address_family==4)) | first | .address')
gateway_ipv4=$(curl -sf https://metadata.platformequinix.com/metadata | jq -r '.network.addresses | map(select(.public==true and .address_family==4)) | first | .gateway')

# Apparently, BGP sessions need to be established from the private ip,
# and source address selection gets it wrong
bgp_r="ip r add 169.254.255.0/30 via $gateway_ipv4 src $private_ipv4"
$bgp_r
  
apt-get install -y augeas-tools
  
# Modify /etc/network/interfaces, so it'll work on a reboot too
old_r=$(augtool get "/files/etc/network/interfaces/iface[last()]/post-up" | cut -d "=" -f 2 | sed 's/^ *//g')
echo -e "set \"/files/etc/network/interfaces/iface[last()]/post-up\" \"$old_r && $bgp_r\"\nsave" | augtool
```

Maybe the packet-provided Ubuntu images could ship that route out of the box?

> asking metallb to have a source address option, like most network software
Yeah, that has already happened some time ago in metallb/metallb#670, metallb/metallb#672, metallb/metallb#593, as linked above.

> Or, you can run kube-vip, which we have more and more people at Equinix Metal doing.

It might be because of the way the `METAL_LB` env var or `metalLB` config are named, but I kinda assumed metallb was better supported than kube-vip. Probably the keys there should be renamed?

Also, I'm somewhat more confident with `metallb`, considering it recently got added into Cilium.

**Comment by deitch** [comment]
I am going to close this issue. As discussed, it is not an issue with CPEM so much as EQXM images and BGP routing as a whole. More importantly, CPEM now supports reading the required source and setting it, both in annotations and metallb configmap.
