### ISSUE TITLE
rename/deprecate METAL_LB env / metalLB config

### ISSUE THREAD

**Issue by flokli** [equinix/cloud-provider-equinix-metal#184]
The `METAL_LB` environment variable `metalLB` config key really suggests one should use this with MetalLB.

That's very unintuitive, considering you're right more in favor of using `kube-vip`.

These strings should probably be replaced to something more generic, like `loadbalancer` or `loadbalancer_ipml` (and the old strings still be accepted for backwards compat)

**Comment by deitch** [comment]
@flokli you are 100% right about the confusion in the naming. We thought about it multiple times (that is why it is named `METAL_LB` and not `METALLB`), but couldn't come up with something else that encapsulates both the proper name of the cloud provider (it _is_ Equinix Metal) and the fact that it sets the load balancer.

I guess we could consider `loadBalancer`; I don't much like `loadBalancerImpl` though; `impl` is something we in the engineering world think about and understand, not something that makes is clear to end users.

Would you want to open a PR for it?
