### ISSUE TITLE
CCM doesn't handle nodes with an updated InstanceID

### ISSUE THREAD

**Issue by flokli** [equinix/cloud-provider-equinix-metal#189]
I'm using a similar approach as https://github.com/rawkode/equinix-metal-examples/blob/main/pulumi-k3s/src/index.ts#L34 to stop and start k8s clusters.

Mine has the Equinix Metal CCM installed though.

When the node boots up again, it has the old `metal_device` uuid (`9193afc8-62a2-4dc4-9dae-7d142606ed11`) in its `providerID` field.

It's not possible to change this manually to the new UUID (`b7cca8fb-e114-40d6-b575-7a9284878ab2`):
```
kubectl patch node staging-master -p '{"spec":{"providerID":"equinixmetal://b7cca8fb-e114-40d6-b575-7a9284878ab2"}}'
The Node "staging-master" is invalid: spec.providerID: Forbidden: node updates may not change providerID except from "" to valid
```

When looking at the logs of the CCM, it can be seen it tries to query the API with the old UUID, getting back 404s:

```
I0720 12:53:55.304031       1 bgp.go:100] bgp.reconcileNodes(): add node staging-master
I0720 12:53:55.304034       1 bgp.go:106] bgp.reconcileNodes(): enabling BGP on node staging-master
I0720 12:53:55.304037       1 devices.go:221] called deviceIDFromProviderID with providerID equinixmetal://9193afc8-62a2-4dc4-9dae-7d142606ed11
2021/07/20 12:53:55 [DEBUG] POST https://api.equinix.com/metal/v1/devices/9193afc8-62a2-4dc4-9dae-7d142606ed11/bgp/sessions
E0720 12:53:55.381102       1 bgp.go:109] could not ensure BGP enabled for node staging-master: POST https://api.equinix.com/metal/v1/devices/9193afc8-62a2-4dc4-9dae-7d142606ed11/bgp/sessions: 404 Not found
I0720 12:53:55.381119       1 bgp.go:111] bgp.reconcileNodes(): bgp enabled on node staging-master
I0720 12:53:55.381122       1 bgp.go:114] bgp.reconcileNodes(): setting annotations on node staging-master
I0720 12:53:55.381124       1 devices.go:221] called deviceIDFromProviderID with providerID equinixmetal://9193afc8-62a2-4dc4-9dae-7d142606ed11
2021/07/20 12:53:55 [DEBUG] GET https://api.equinix.com/metal/v1/devices/9193afc8-62a2-4dc4-9dae-7d142606ed11/bgp/neighbors?
E0720 12:53:55.462055       1 bgp.go:118] bgp.reconcileNodes(): could not get BGP info for node staging-master: failed to get device neighbours for device 9193afc8-62a2-4dc4-9dae-7d142606ed11: GET https://api.equinix.com/metal/v1/devices/9193afc8-62a2-4dc4-9dae-7d142606ed11/bgp/neighbors?: 404 Not found
I0720 12:53:55.462067       1 bgp.go:178] bgp.reconcileNodes(): complete
```

This means, it doesn't re-enable BGP for that server, doesn't add its config to the metallb configmap, can't bring up a BGP, and thus can't bring back up the control plane. I omitted the log lines about that.

Is there a way for the CCM to update/clear the instance ID, in case it seems to be wrong?

**Comment by flokli** [comment]
I was able to workaround this by adding some randomness into the hostname. That way, a /new/ Node resource is created for the new master, with an unpopulated InstanceID field.

I still wonder if this is the desired behaviour - is InstanceID supposed to be write-once?

**Comment by deitch** [comment]
> It's not possible to change this manually to the new UUID

yeah, as far as I know, `providerID` is immutable. 

> When looking at the logs of the CCM, it can be seen it tries to query the API with the old UUID, getting back 404s:

Right. It uses the providerID in various places and if that doesn't exist, gets back 404s.

It sets it [here](https://github.com/equinix/cloud-provider-equinix-metal/blob/master/metal/devices.go#L102) where it is called by the cloud-provider framework, gives it the node name and gets the device ID. If it already has it, it doesn't bother with that.

This is more fundamental than the CCM. k8s assumes that an instance has a provider ID, that it sets it via CCM, and that once it is set, it is immutable. Restoring a cluster from etcd - including the nodes and their properties, including providerID - breaks this. 

I would turn towards the k8s folks (either an issue on the repo or in the k8s slack) and ask about restoring a cluster including nodes. I suspect they would say, "don't restore nodes", because you really are _not_ restoring the nodes, but rather getting new ones.

**Comment by flokli** [comment]
> This is more fundamental than the CCM. k8s assumes that an instance has a provider ID, that it sets it via CCM, and that once it is set, it is immutable. Restoring a cluster from etcd - including the nodes and their properties, including providerID - breaks this.

Yeah, seems this is not a EQXM-specific issue.

> I would turn towards the k8s folks (either an issue on the repo or in the k8s slack) and ask about restoring a cluster including nodes. I suspect they would say, "don't restore nodes", because you really are not restoring the nodes, but rather getting new ones.

I guess the reply here would be to restore the cluster state, but "be a new master node" - as I did [workaround here](https://github.com/equinix/cloud-provider-equinix-metal/issues/189#issuecomment-883578280).

Thanks for the clarification! Let's close this here.
