### ISSUE TITLE
`printMetalConfig` doesn't redact secrets

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#213]
`printMetalConfig` doesn't redact secrets

Redact secrets or change/remote the debugging code.

_Originally posted by @deitch in https://github.com/equinix/cloud-provider-equinix-metal/pull/185#discussion_r737204298_

**Comment by deitch** [comment]
I think it actually does. The [Config](https://github.com/equinix/cloud-provider-equinix-metal/blob/07d26f4d2f532621e78e3dcb021651b5e98c72ee/metal/config.go#L38-L59) only has one truly sensitive field, `AuthToken`. When [printMetalConfig](https://github.com/equinix/cloud-provider-equinix-metal/blob/07d26f4d2f532621e78e3dcb021651b5e98c72ee/metal/config.go#L198-L203) wants to print it, it calls [config.Strings()](https://github.com/equinix/cloud-provider-equinix-metal/blob/07d26f4d2f532621e78e3dcb021651b5e98c72ee/metal/config.go#L199), which [removes the token](https://github.com/equinix/cloud-provider-equinix-metal/blob/07d26f4d2f532621e78e3dcb021651b5e98c72ee/metal/config.go#L66-L70).

Nothing else sensitive is printed. I think we can close this. @displague ?
