### ISSUE TITLE
Missing Developer Certificate of Origin!

### ISSUE THREAD

**Issue by robertvolkmann** [equinix/cloud-provider-equinix-metal#218]
According to [CONTRIBUTING.md](https://github.com/equinix/cloud-provider-equinix-metal/blob/master/CONTRIBUTING.md) I have to review the Developer Certificate of Origin to do any contribution but this repository has no Developer Certificate of Origin!

**Comment by displague** [comment]
Thanks for pointing this out, @robertvolkmann . I've opened a PR with a fix to the CONTRIBUTING.md guide. This refers to the DCO hosted at https://developercertificate.org/
