### ISSUE TITLE
document kube-vip version compatibility matrix

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#226]
Users have reported confusion aligning versions of kube-vip with CPEM.

In the documentation, we should point out which versions of kube-vip/metallb are compatible (recommended!) with the versions of CPEM.  This could be included in the k8s version table.

 https://github.com/equinix/cloud-provider-equinix-metal#version

Kube-vip may also need to take on this responsibility, documenting which versions of CPEM are compatible with the CPEM annotations that kube-vip is aware of.

**Comment by ctreatma** [comment]
Closed by #381
