### ISSUE TITLE
Publish images to a location other than docker hub

### ISSUE THREAD

**Issue by detiber** [equinix/cloud-provider-equinix-metal#233]
With the dockerhub pull limits in place it is relatively easy to get into a situation where a node is not able to pull the CPEM image from docker hub, especially in cases involving automated testing.

As a result, I think it would be a good idea to start publishing images to another public registry.

ghcr.io would be relatively straight forward, since we could automate publishing the image using secrets that are injected automatically into github actions.

We will probably need to continue to publish images to dockerhub for existing users (especially when using the helm charts).

The helm chart can be updated to make the registry/image configurable.

We would need to decide whether to push older images to ghcr.io as well, or if it would only be newer images.

**Comment by deitch** [comment]
I like this. A lot. We definitely should push to ghcr.io, although I would think about quay as well. Should we do gcr.io? Do they support free public images?

**Comment by deitch** [comment]
Maybe it is time for "eqxmcr"? :-)

**Comment by detiber** [comment]
I'm not aware of any free tier for gcr.io, but we can definitely throw quay.io into the mix as well, that's what we primarily use for Tinkerbell projects.

**Comment by detiber** [comment]
As of #234 merging we are now publishing to dockerhub and ghcr.io for post-submits. The next release should also publish to these two registries as well.

The only thing remaining to publish to quay.io would be to add the credentials needed for the quay.io/equinix org to the secrets configuration as `QUAY_USERNAME` and `QUAY_PASSWORD`. If we wanted to use an org name different than `equinix` for quay.io, then the workflows would need to be modified to account for that. We could potentially add `DOCKER_ORG` and `QUAY_ORG` as a way to override the use of the name of the repo org today if we wanted to provide more flexibility for this type of configuration.

**Comment by displague** [comment]
Can we close this now that [ghcr](https://ghcr.io/equinix/cloud-provider-equinix-metal) is available?

**Comment by deitch** [comment]
I left it open as we wanted to do quay as well. We actually have the ability to publish there now.

**Comment by detiber** [comment]
Created a PR to enable this based on the work I've been doing for CAPP: https://github.com/equinix/cloud-provider-equinix-metal/pull/250

Testing it now in my own fork, but will need the following additional secrets set to work:
- DOCKER_ORG
- QUAY_ORG
- QUAY_USERNAME
- QUAY_PASSWORD

**Comment by detiber** [comment]
This has now been completed, now that #250 has merged and the workflow has run successfully.
