### ISSUE TITLE
Publish a new release to support CAPP release

### ISSUE THREAD

**Issue by detiber** [equinix/cloud-provider-equinix-metal#243]
For the CAPP release, we need an updated release of CPEM that includes the EIP fixes that were recently merged.

**Comment by deitch** [comment]
Agreed. From a technical perspective, this is just a minor release. From a marketing one, might be major. 

I'll cut a release a little later today. 

Is there anything else you can think of that we should wait for? Is the quay.io worth waiting for?

We also should put together a list of changes for the release notes, and get it in the announcements. Anything you want in there?

**Comment by detiber** [comment]
> Is there anything else you can think of that we should wait for? Is the quay.io worth waiting for?

I'm not aware of anything that should hold up the release and definitely don't think quay.io is an immediate concern.

> We also should put together a list of changes for the release notes, and get it in the announcements. Anything you want in there?

I'd definitely call out the updates for the cloud-provider interface (Instancesv2 support and proper LoadBalancer support), as well as the improved control plane EIP management.

**Comment by deitch** [comment]
Done with https://github.com/equinix/cloud-provider-equinix-metal/releases/tag/v3.4.0
