### ISSUE TITLE
Helm chart 

### ISSUE THREAD

**Issue by TimJones** [equinix/cloud-provider-equinix-metal#312]
I assume due to #169 that the Helm Chart in this repo shouldn't be considered ready for use.

Before it gets published anywhere I noticed that the `template/deployment.yaml` is actually a DaemonSet, so it should be renamed accordingly. Also the DaemonSet resources does not support a `replicas` field in the spec.

**Comment by deitch** [comment]
Yeah, that was a recent update. I don't care _all_ that much if the file is named `deployment.yaml` or `daemonset.yaml`, but it is good hygiene to clean it up.

Most of the testing happens from the direct manifests, not from the Helm chart. We really should auto-generated one from the other, and then we are in a reliable channel all the way through.
