### ISSUE TITLE
[Bug] CPEM fails to sync service when additional service is in default namespace

### ISSUE THREAD

**Issue by Lirt** [equinix/cloud-provider-equinix-metal#380]
Hello,

When there is another service in `default` namespace, CPEM gets confused by it and does healthcheck (`doHealthCheck()`) using port specified by it instead of `default/kubernetes`.

In my instance I have additional service created by grafana-agent in default namespace:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kubelet
  labels:
    app.kubernetes.io/managed-by: grafana-agent-operator
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
spec:
  type: ClusterIP
  ports:
  - targetPort: https-metrics
    port: 10250
    name: kubelet
  - targetPort: https-metrics
    port: 10255
    name: kubelet-read-only
  - targetPort: cadvisor
    port: 4194
    name: cadvisor
```

After this service was created CPEM log started to output this:
```sh
I0301 06:56:58.137339       1 eip_controlplane_reconciliation.go:206] handling update, service: default/kubelet
E0301 06:56:58.331549       1 eip_controlplane_reconciliation.go:135] failed to handle node health check: failed to assign the control plane endpoint: POST https://api.equinix.com/metal/v1/devices/0aeb3ae2-1c24-4718-9b39-a129e29e453e/ips: 500 Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble. 
I0301 06:56:58.331594       1 eip_controlplane_reconciliation.go:125] handling update, node: iot-equinix-01-control-plane-c79zn
E0301 06:56:59.035057       1 eip_controlplane_reconciliation.go:209] failed to sync service from default/kubernetes to kube-system/cloud-provider-equinix-metal-kubernetes-external: failed to apply service kube-system/cloud-provider-equinix-metal-kubernetes-external: Service "cloud-provider-equinix-metal-kubernetes-external" is invalid: spec.ports[0]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet
I0301 06:56:59.408680       1 eip_controlplane_reconciliation.go:521] doHealthCheck(): no control plane IP assignment found, trying to assign to an available controlplane node
I0301 06:56:59.412585       1 eip_controlplane_reconciliation.go:242] healthcheck node https://10.68.53.139:10250/healthz
I0301 06:56:59.414836       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-c79zn: returned http code 401
I0301 06:56:59.414843       1 eip_controlplane_reconciliation.go:242] healthcheck node https://147.28.128.229:10250/healthz
I0301 06:56:59.417049       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-c79zn: returned http code 401
I0301 06:56:59.417056       1 eip_controlplane_reconciliation.go:242] healthcheck node https://10.68.53.131:10250/healthz
I0301 06:56:59.420457       1 eip_controlplane_reconciliation.go:276] will not assign control plane endpoint to new device iot-equinix-01-control-plane-ws7kt: returned http code 401
I0301 06:56:59.420467       1 eip_controlplane_reconciliation.go:242] healthcheck node https://147.28.146.199:10250/healthz
```

As you can see for some reason it tries to apply service having port 10250 - `failed to apply service kube-system/cloud-provider-equinix-metal-kubernetes-external: Service "cloud-provider-equinix-metal-kubernetes-external" is invalid: spec.ports[0]: Invalid value: 10250: may not expose port 10250 externally since it is used by kubelet`.

Then additionally healthchecks started to use port `10250` and started to fail (correct port is 6443).

All this resulted into losing EIP assignment and losing access to control plane over load balancer created by CAPM. After service is deleted, CPEM starts to work correctly - so this is very easy to reproduce.

If you need any additional info, please let me know.

**Comment by displague** [comment]
The health check code changes were introduced in https://github.com/equinix/cloud-provider-equinix-metal/pull/230 where there is some discussion that may be relevant.

**Comment by displague** [comment]
https://github.com/equinix/cloud-provider-equinix-metal/blob/8cc2e100bdabe7ea2a680af72a4a6398ec3ea90e/metal/eip_controlplane_reconciliation.go#L456-L457 is where the first defined port is assumed. Perhaps we should ensure that the port name matches the expected value. Is `https` the port name we want?

**Comment by Lirt** [comment]
Hi, 

I'm not super familiar with codebase, but before opening issue I went over the code. For me what I don't understand is how it got to the point that service uses port 10250, when there is [FilterFunc](https://github.com/equinix/cloud-provider-equinix-metal/blob/f6bc01ef68bb8f595552a5464e0943254dec82e0/metal/eip_controlplane_reconciliation.go#L185-L216) (see code) that should return only service `default/kubernetes`.


This is in the log. That means that service even though `default/kubelet` should be filtered out, the `Handler.AddFunc()` is processed.
```sh
I0301 17:24:39.918984       1 eip_controlplane_reconciliation.go:206] handling update, service: default/kubelet
I0301 17:24:39.919137       1 eip_controlplane_reconciliation.go:173] handling update, endpoints: default/kubernetes
```

I think this was not desired.

**Comment by displague** [comment]
Potentially unrelated: Walking through the process and potential traps, if an EIP is assigned to multiple hosts it will not be unassigned appropriately before reassignment is attempted.  Unassigning in a for-loop may be a better approach here:

https://github.com/equinix/cloud-provider-equinix-metal/blob/8cc2e100bdabe7ea2a680af72a4a6398ec3ea90e/metal/eip_controlplane_reconciliation.go#L263-L267

**Comment by displague** [comment]
https://github.com/equinix/cloud-provider-equinix-metal/blob/8cc2e100bdabe7ea2a680af72a4a6398ec3ea90e/metal/eip_controlplane_reconciliation.go#L233-L237 seems to be agnostic to the type of IP - public, private, or IPv6.  Since all addresses registered with the node should be listening, this seems ok.

**Comment by displague** [comment]
@Lirt I think you spotted it. https://github.com/equinix/cloud-provider-equinix-metal/blob/8cc2e100bdabe7ea2a680af72a4a6398ec3ea90e/metal/eip_controlplane_reconciliation.go#L189 may have the wrong logic to capture `default/kubernetes` in the presence of additional services.  The `&&` should be `||` or the logic should be simplified to return true only on `default/kubernetes`.

**Comment by cprivitere** [comment]
So resolutions could be
```
			FilterFunc: func(obj interface{}) bool {
				s, _ := obj.(*v1.Service)
				if s.Namespace == metav1.NamespaceDefault && s.Name != "kubernetes" {
					return true
				}

				return false
			},
```
vs
```
			FilterFunc: func(obj interface{}) bool {
				s, _ := obj.(*v1.Service)
				if s.Namespace != metav1.NamespaceDefault || s.Name != "kubernetes" {
					return false
				}

				return true
			},
```
I like the first one more. Thoughts?

**Comment by Lirt** [comment]
Sorry to run into discussion but isn't the point to do the `m.syncService` only for service `default/kubernetes`? :smile: 

```go
    // Filter only service default/kubernetes
    if s.Namespace == metav1.NamespaceDefault && s.Name == "kubernetes" {
        return true
    }
    // else
    return false
```

**Comment by cprivitere** [comment]
Yeah, updated above, thanks.

**Comment by displague** [comment]
An additional concern in this error report is:
> failed to handle node health check: failed to assign the control plane endpoint: POST https://api.equinix.com/metal/v1/devices/.../ips: 500 Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble. 

This error scenario appears to be retried too frequently. This may be amplified by the number of nodes in the cluster.

**Comment by Lirt** [comment]
Thank you very much for all support. :pray:
