### ISSUE TITLE
Rebrand: Packet to Equinix Metal

### ISSUE THREAD

**Issue by rainleander** [equinix/cloud-provider-equinix-metal#90]
Packet was acquired by Equinix in March. To help make our vision for global, interconnected bare metal a reality, we've rebranded Packet as Equinix Metal™ and introduced new locations and features. Login, sign up, and say hello at metal.equinix.com. Example rebrands:

Packet --> Equinix Metal
support@packethost.com --> support@equinixmetal.com
https://slack.packet.com/ --> https://slack.equinixmetal.com/
Freenode IRC #packethost --> Freenode IRC #equinixmetal
packet.com --> metal.equinix.com
https://app.packet.net/ --> https://console.equinix.com/

**Comment by deitch** [comment]
We have a bunch of business-critical changes going in this week and next. As soon as those are done and a release is cut, we should address these documentation issues.

**Comment by rainleander** [comment]
Perfect; thx!

**Comment by deitch** [comment]
Complete with #137
