### ISSUE TITLE
Create and manage Helm chart for packet-ccm

### ISSUE THREAD

**Issue by knrt10** [equinix/cloud-provider-equinix-metal#92]
It would be nice if there is a helm chart for the deployment and loadbalancer converted to approproate files. What do you think @deitch?

**Comment by displague** [comment]
CCMs are generally installed while the nodes are un-schedulable without certain tolerations. Is Helm able to run in this early stage?

**Comment by knrt10** [comment]
In Lokomotive we have successfully added the helm charts, to solve the scheduling problem we are installing it while bootstrapping the cluster so that it works https://github.com/kinvolk/lokomotive/pull/1155/commits/2e7f69625331d5c23ca3c20d16f56fe3fb892fcb

**Comment by displague** [comment]
I just (re)discovered https://github.com/packet-labs/helm-charts

The CSI driver is deprecated, so perhaps the helm-charts project can be archived if CCM helm publishing takes effect in this project.

I don't see how or where these charts are published in the helm-charts project (there are no releases).

The helm charts published in this project would be attached to releases, assuming that is an effective way to distribute and update helm charts (and perhaps it is not, perhaps we would use a github.io domain).

On the other hand, a equinix.github.io/helm-charts would be a nice centralized location for other charts (cluster API, crossplane, etc). Syncing changes across projects may create more concerns.

Thoughts @deitch, @jmarhee?

**Comment by deitch** [comment]
Yeah, CSI is deprecated, all that is left in that repo is CCM, and it probably . We should do what you suggest, in this order:

1. merge in #166 
1. add automatic CI for releases of the helm chart in this repo
1. update that other repository to remove CSI and point to the CCM in this repo
2. if we can, have that other repo automatically update from this repo, so we have a centralized place
3. migrate that other repo to `equinix/helm-charts` so we have that one centralized place
